const Products = [
  {
    name: "Banarasi Gold Saree",
    description: "Luxurious Banarasi silk saree with golden zari work.",
    price: 4500,
    category: "Handloom",
    image: "banarasi-gold.jpg",
    stock: 15,
  },
  {
    name: "Chikankari Kurta",
    description: "Elegant hand-embroidered Chikankari kurta.",
    price: 1800,
    category: "Handloom",
    image: "chikankari-kurta.jpg",
    stock: 25,
  },
  {
    name: "Designer Bridal Lehenga",
    description: "Premium bridal lehenga with intricate embroidery.",
    price: 12000,
    category: "Handloom",
    image: "designer-lehenga.jpg",
    stock: 5,
  },
  {
    name: "Indo-Western Gown",
    description: "Fusion gown blending Indian and Western styles.",
    price: 6000,
    category: "Handloom",
    image: "indo-western-gown.jpg",
    stock: 8,
  },
  {
    name: "Kanchipuram Bridal Saree",
    description: "Rich bridal saree with temple borders.",
    price: 9500,
    category: "Handloom",
    image: "kanchipuram-bridal.jpg",
    stock: 10,
  },
  {
    name: "Kanchipuram Royal Saree",
    description: "Royal silk saree with heritage motifs.",
    price: 8500,
    category: "Handloom",
    image: "kanchipuram-royal.jpg",
    stock: 10,
  },
  {
    name: "Pashmina Shawl",
    description: "Soft Kashmiri pashmina shawl crafted by artisans.",
    price: 5500,
    category: "Handloom",
    image: "pashmina-shawl.jpg",
    stock: 15,
  },
  {
    name: "Kerala Kasavu Saree",
    description: "Traditional white and gold Kerala kasavu saree.",
    price: 3200,
    category: "Handloom",
    image: "kasavu.jpg",
    stock: 20,
  },
  {
    name: "Banarasi Silk Dupatta",
    description: "Elegant woven silk dupatta for festive wear.",
    price: 1900,
    category: "Handloom",
    image: "banarasi-dupatta.jpg",
    stock: 18,
  },
  {
    name: "Handloom Cotton Kurti",
    description: "Breathable handloom cotton kurti for daily elegance.",
    price: 1400,
    category: "Handloom",
    image: "cotton-kurti.jpg",
    stock: 30,
  },

  {
    name: "Traditional Jewellery Set",
    description: "Authentic Indian jewellery set for festive occasions.",
    price: 8000,
    category: "Jewellery",
    image: "jewellery-set.jpg",
    stock: 12,
  },
  {
    name: "Temple Jewellery Necklace",
    description: "Gold-plated temple necklace inspired by South Indian heritage.",
    price: 9000,
    category: "Jewellery",
    image: "temple-necklace.jpg",
    stock: 7,
  },
  {
    name: "Kundan Choker",
    description: "Exquisite kundan choker with pearl detailing.",
    price: 7000,
    category: "Jewellery",
    image: "kundan-choker.jpg",
    stock: 6,
  },
  {
    name: "Meenakari Bangles",
    description: "Colorful meenakari bangles handcrafted by artisans.",
    price: 1500,
    category: "Jewellery",
    image: "meenakari-bangles.jpg",
    stock: 20,
  },
  {
    name: "Antique Jhumka Earrings",
    description: "Vintage style jhumkas with traditional detailing.",
    price: 1200,
    category: "Jewellery",
    image: "jhumka.jpg",
    stock: 25,
  },
  {
    name: "Bridal Maang Tikka",
    description: "Elegant maang tikka for bridal and festive looks.",
    price: 1800,
    category: "Jewellery",
    image: "maang-tikka.jpg",
    stock: 14,
  },

  {
    name: "Brass Nilavilakku Lamp",
    description: "Traditional Kerala brass lamp for auspicious occasions.",
    price: 3500,
    category: "Decor",
    image: "nilavilakku.jpg",
    stock: 10,
  },
  {
    name: "Kathakali Wall Mask",
    description: "Handcrafted Kathakali face mask wall decor.",
    price: 1600,
    category: "Decor",
    image: "kathakali-mask.jpg",
    stock: 15,
  },
  {
    name: "Brass Urli Bowl",
    description: "Decorative brass urli bowl for floating flowers.",
    price: 2400,
    category: "Decor",
    image: "urli.jpg",
    stock: 12,
  },
  {
    name: "Wooden Elephant Carving",
    description: "Hand-carved wooden elephant for home decor.",
    price: 2100,
    category: "Decor",
    image: "wood-elephant.jpg",
    stock: 10,
  },
  {
    name: "Handcrafted Wall Hanging",
    description: "Traditional Indian textile wall hanging.",
    price: 1300,
    category: "Decor",
    image: "wall-hanging.jpg",
    stock: 18,
  },

  {
    name: "Wedding Flower Garland",
    description: "Traditional garland for weddings and ceremonies.",
    price: 800,
    category: "Wedding",
    image: "garland.jpg",
    stock: 25,
  },
  {
    name: "Mehendi Ceremony Tray",
    description: "Decorated tray for mehendi ceremonies.",
    price: 1400,
    category: "Wedding",
    image: "mehendi-tray.jpg",
    stock: 12,
  },
  {
    name: "Groom Wedding Safa",
    description: "Royal groom turban for wedding attire.",
    price: 1100,
    category: "Wedding",
    image: "safa.jpg",
    stock: 15,
  },
  {
    name: "Bridal Potli Bag",
    description: "Embroidered potli bag for bridal occasions.",
    price: 950,
    category: "Wedding",
    image: "potli.jpg",
    stock: 20,
  },
    {
    name: "Brass Annam Vilakk",
    description: "Traditional Kerala brass lamp featuring the sacred swan (Annam) motif, symbolizing prosperity and purity. Perfect for pooja rooms and festive decor.",
    price: 4200,
    category: "Decor",
    image: "vilakk.jpg",
    stock: 8,
  },
  
  {
    name: "Chanderi Brown Designer Saree",
    description: "Lightweight Chanderi saree in rich brown tone with delicate zari patterns, offering a graceful festive look.",
    price: 5200,
    category: "Handloom",
    image: "chanderi.jpg",
    stock: 14,
  },
  {
    name: "Organza Bordered Chanderi Saree",
    description: "Soft Chanderi saree enhanced with a sheer organza border for a contemporary and elegant finish.",
    price: 6400,
    category: "Handloom",
    image: "organza-chanderi.jpg",
    stock: 9,
  },
  {
    name: "Bottle Green Embroidered Saree",
    description: "Rich bottle green saree featuring fine embroidery and subtle shimmer, perfect for evening functions.",
    price: 5600,
    category: "Handloom",
    image: "bottlegreen.jpg",
    stock: 12,
  },
  {
    name: "White Anarkali with Golden Work",
    description: "Flowing white Anarkali suit embellished with delicate golden embroidery, creating a royal festive appearance.",
    price: 4800,
    category: "Handloom",
    image: "anarkali.jpg",
    stock: 16,
  },
  {
    name: "Red Vermillion Cotton Blend Saree",
    description: "Vibrant vermillion red saree crafted from a cotton-polyester blend, offering comfort with a striking traditional look.",
    price: 2600,
    category: "Handloom",
    image: "red-saree.jpg",
    stock: 20,
  },
  {
    name: "White Saree with Pastel Blouse",
    description: "Graceful white saree paired with a soft pastel blouse, delivering a minimalist and elegant aesthetic.",
    price: 3100,
    category: "Handloom",
    image: "white-saree.jpg",
    stock: 18,
  },
  {
  name: "Golden Silk Saree",
  price: 4599,
  description: "Elegant golden silk saree with traditional zari border, perfect for weddings and festive occasions.",
  category: "Handloom",
  stock: 12,
  image: "golden.jpg",
  color: "Gold",
  size: "Free Size",
  material: "Silk"
}
];
export default Products; 